name: count_down_time
description: A count-down timer package with options to reset and set current time.
version: 0.0.7
homepage: https://github.com/emirdeliz/count_down_time

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=2.5.0"

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
